#pragma once

#include "NativeGameplayTags.h"

namespace KCUITags
{
	PROJECTKC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Game);
	PROJECTKC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Menu);
	PROJECTKC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_GameMenu);
	PROJECTKC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Modal);
	PROJECTKC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_System);
	PROJECTKC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Toast);
	PROJECTKC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Indicator);
	PROJECTKC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Layer_Transition);
}
