;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Item.Id.FryingPan",DevComment="Frying pan item type")
+GameplayTagList=(Tag="Item.Id.Fan",DevComment="Fan item type")
+GameplayTagList=(Tag="Item.Id.Test1",DevComment="")
+GameplayTagList=(Tag="Item.Id.Test2",DevComment="")
+GameplayTagList=(Tag="Item.Id.Test3",DevComment="")
+GameplayTagList=(Tag="Item.Id.Test4",DevComment="")
+GameplayTagList=(Tag="Item.Id.Test5",DevComment="")

