#pragma once

#include "NativeGameplayTags.h"

// 행동의 어느 순간인가. 대상 종류는 ActionTargeting과 Fragment Scope가 정한다.
PROJECTKC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KC_ActionHook_OnStart);
PROJECTKC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KC_ActionHook_OnExecute);
PROJECTKC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KC_ActionHook_OnComplete);

PROJECTKC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KC_GameplayEvent_AbilitySource_Trigger);
PROJECTKC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KC_GameplayEvent_Action_Execute);

PROJECTKC_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_KC_Data_Damage_Flat);
